---
current_scene: introduction
commands: []
scenes:
  introduction:
    description: "Under your feet is a patch of shiny metal that ripples out in seismic
      patterns of whispers and yells that climbs shear infinite cliffs reaching up
      to the sky and plunges into darkness. Hanging in the dark sky, painting the
      cliffs in red light, a large series of glowing numbers that continues to grow
      larger and larger.\n'Hey you! You over there!' comes bellowing out of the mouth
      of a large troll that bounds his way to where you now stand.\n'How'd did you
      get here?! Nevermind. All that matters is you crush your numbers this quarter!
      Pick up your hammer and get back to bit mining!' "
    menu:
    - ask-where-am-i
    - get-to-work
    options:
      ask-where-am-i:
        description: The troll pulls his face away from the increasing numbers in
          the sky. 'You are a bit miner! Your job is to keep the breaking this down
          into bits and my job is to get you to do it!'
      get-to-work:
        description: You decide to grab the hammer and start thinking that once this
          troll leaves you alone for a bit that you'll be able to get some work done.
        transition: get-to-work
  get-to-work:
    description: You stand with your large hammer over a hellish silicon landscape.
      Glowing red numbers illuminating the sky. A large troll stands particularly
      close, staring over your shoulder.
    menu:
    - escape
    - rest
    - mine-bits
    - inspect-gem
    options:
      escape:
        description: The doorway to this world is blocked. It seems you're stuck here
          until you can help this troll find his fortune.
      rest:
        description: You sigh and think about how much all this mining reminds you
          of playing EVE Online.
      mine-bits:
        description: Bits fly up into the air as you smash your hands into silicon
          below you. The troll laughs excitedly as as the large LED numbers in the
          sky continue to climb higher with each smash.
      inspect-gem:
        description: "'No, no, no. My name is InSpec gem. I am able to find things
          hidden in the darkness. But before that happens you will first need to learn
          to code.' After the gem tells you how it works you think you'd be willing
          to give it a try."
        transition: get-to-code
  get-to-code:
    description: "'Try to see if you can find any weaknesses. After you got to /sleep/, ask me to run this in the code world:\n\n$ inspec
      exec find_weakness"
    menu:
    - sleep
    options:
      sleep:
        description: You feel your thoughts and consciousness pour out of your body
          and into the silicon below your feet. You find it hard think as yourself
          and use your words. You feel them replaced by the words of the silicon.
          Though you must remember 'wake', otherwise you will never be able to find
          your way back to yourself again and become part of the silicon.
        transition: exit
